version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: foo
    ports:
      - "15432:5432"
  web:
    build: .
    command: /usr/src/api/docker/wait-for-db.sh npm run docker:run
    environment:
      NODE_ENV: "docker"
      DEBUG: "email"
    links:
      - postgres:postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ..:/usr/src/api
      - ../../UI:/usr/src/UI
