version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: foo
    ports:
      - "3306:3306"
  web:
    build: .
    command: "/usr/src/app/scripts/run.sh"
    environment:
      NODE_ENV: "docker"
    links:
      - mysql:mysql
    ports:
      - "8000:8000"
    depends_on:
      - mysql
