version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: foo
    ports:
      - "15432:5432"
  web:
    build: .
    command: npm start
    environment:
      NODE_ENV: "docker"
    links:
      - postgres:postgres
    ports:
      - "8001:8001"
    depends_on:
      - postgres
